### ISSUE TITLE
I have an issue, so need your help.

### ISSUE THREAD

**Issue by samurai-techlead** [andrew-fleming/project-coinflip-v-6#6]
I used this repo and tested on polygon mumbai testnet.
I deployed the contract and integrated with React
When I call the flip function using web3.js, the transaction is reverted, So, I am looking for your reply.
![image](https://user-images.githubusercontent.com/95104528/161221909-2fe3c4c8-8626-40fb-a5f4-36db0b4b05c8.png)

**Comment by andrew-fleming** [comment]
Hey @YukioDev85, I don't believe the Provable oracle supports queries to the Mumbai network. Try running this on Ropsten, Kovan, or Rinkeby.

**Comment by YukioDev85** [comment]
Thanks for your kind reply.
I will check then will let you know.
Thanks again.

**Comment by andrew-fleming** [comment]
My pleasure :)

**Comment by YukioDev85** [comment]
**@andrew-fleming**
I am not sure, but in my opinion, to generate random in polygon, we should use the chainlink instead provable oracle.
How do you think?

**Comment by andrew-fleming** [comment]
I totally agree! I made the coinflip dapp a long time ago. If you'd like to see an application using Chainlink, check out the [pmkn-farm repo](https://github.com/andrew-fleming/pmkn-farm). I wrote a tutorial for the basics [here](https://medium.com/coinmonks/yield-farming-tutorial-part-1-3fd5972ce717) (not including the NFT and lottery features). And here's the docs for integrating [Chainlink's VRF](https://docs.chain.link/docs/chainlink-vrf/).

**Comment by samurai-techlead** [comment]
Thanks for your kind.

**Comment by YukioDev85** [comment]
Hi! there.
I have a question.
I deployed to the mumbai and I used the chainlink.
But, when I try to call the flip function, error is discovered.
Maybe, I am not so familiar with chainlink, so, this issue is discoverd.
So, I need your help.
Which part is wrong....
pragma solidity ^0.6.6;
 
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";

contract Coinflip is VRFConsumerBase {
    using SafeMathChainlink for uint256;
    struct Bet {
        address playerAddress;
        uint betValue;
        uint headsTails;
        
    }
    
    mapping(address => uint) public playerWinnings;
    mapping (address => Bet) public waiting;
    mapping (bytes32 => address) public afterWaiting;
    
    event logNewProvableQuery(string description);
    event sentQueryId(address caller, bytes32 indexed queryId);
    event callbackReceived(bytes32 indexed queryId, string description, uint256 amount);
    event userWithdrawal(address indexed caller, uint256 amount);

    bytes32 internal keyHash;
    uint256 internal fee;

    uint public contractBalance;
    
    uint256 constant GAS_FOR_CALLBACK = 200000;
    uint256 constant NUM_RANDOM_BYTES_REQUESTED = 1;
    
    address payable public owner = msg.sender;
   
    bool public freeCallback = true;

    constructor() VRFConsumerBase(
            0x8C7382F9D8f56b33781fE506E897a4F1e2d17255,
            0x326C977E6efc84E512bB9C30f76E30c160eD06FB
        ) public payable {
        owner = msg.sender;
        contractBalance = msg.value;
        keyHash = 0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4;
        fee = 100000000000000; // 0.0001 LINK
    }
    
    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }
    
    /**
    * @param oneZero - The numerical value of heads(0) or tails(1)
    */

    function flip(uint256 oneZero) public payable {
        require(contractBalance > msg.value, "We don't have enough funds");        

         bytes32 queryId = _getRequestId();
        emit logNewProvableQuery("Message sent. Waiting for an answer...");
        emit sentQueryId(msg.sender, queryId);

        afterWaiting[queryId] = msg.sender;

        Bet memory newBetter;
        newBetter.playerAddress = msg.sender;
        newBetter.betValue = msg.value; 
        newBetter.headsTails = oneZero;
        
        waiting[msg.sender] = newBetter;
        flipCoin();
    }

    function flipCoin() public returns (bytes32) {
        return requestRandomness(keyHash, fee, block.timestamp);
    }
    
    /**
     * Callback function used by VRF Coordinator
     */
    function fulfillRandomness(bytes32 requestId, uint256 randomness)
        internal
        override
    {
        // 0 = heads = false
        // 1 = tails = true
        uint result = randomness % 2;
        address _player = afterWaiting[requestId];
        
        Bet memory postBet = waiting[_player];
    
        if(result == postBet.headsTails){
            //winner
            // uint winAmount = SafeMath.sub(SafeMath.mul(postBet.betValue, 2), postBet.setRandomPrice); 
            // uint winAmount = postBet.betValue.mul(2); 
            // contractBalance = contractBalance.sub(postBet.betValue);
            // playerWinnings[_player] = playerWinnings[_player].add(winAmount);         
            emit callbackReceived(requestId, "Winner", postBet.betValue);
        } else {
            //loser
            // contractBalance = contractBalance.add(postBet.betValue);            
            emit callbackReceived(requestId, "Loser", postBet.betValue);
        }        
    }    
    
    function _getRequestId() internal view returns (bytes32) {
        uint256 nonce = nonces[keyHash];
        uint256 preSeed = makeVRFInputSeed(
            keyHash,
            block.timestamp,
            address(this),
            nonce
        );
        return makeRequestId(keyHash, preSeed);
    }
    
    function withdrawUserWinnings() public {
        require(playerWinnings[msg.sender] > 0, "No funds to withdraw");
        uint toTransfer = playerWinnings[msg.sender];
        playerWinnings[msg.sender] = 0;
        msg.sender.transfer(toTransfer);
        emit userWithdrawal(msg.sender, toTransfer);
    }
    
    function getWinningsBalance() public view returns(uint){
        return playerWinnings[msg.sender];
    }
    
    /**
    *@notice The following functions are reserved for the owner of the contract.
     */
    
    function fundContract() public payable onlyOwner {
        contractBalance = contractBalance.add(msg.value);
    }
    
    function fundWinnings() public payable onlyOwner {
        playerWinnings[msg.sender] = playerWinnings[msg.sender].add(msg.value);
    }
    
    function withdrawAll() public onlyOwner {
        uint toTransfer = contractBalance;
        contractBalance = 0;
        msg.sender.transfer(toTransfer);
    }

}

**Comment by andrew-fleming** [comment]
Hmm it's difficult to tell. What's the error exactly? Also, it might be a good idea to create tests for your contract to ensure each method behaves appropriately. In retrospect, this was bad form on my part for not including tests in the repo years ago.

**Comment by samurai-techlead** [comment]
To use the chainlink vrf, need the link token?

**Comment by andrew-fleming** [comment]
Ah yes. You can get it [here](https://faucet.polygon.technology/).

**Comment by YukioDev85** [comment]
I tried wtih Link Token, error is disappeared but I can't listen the reandomess in fullfillrandomess function.
Could you explain about that?

**Comment by andrew-fleming** [comment]
Of course. So, these requests may take a moment or two because you're sending a request over the network, the Chainlink oracle has to process the request, and then send a tx back over the network. They're actually calling the `fulfillRandomness` method on your contract. You can follow the tx chain through the [Mumbai block explorer](https://mumbai.polygonscan.com/). To better understand the process and ensure you're doing it correctly, I recommend using Remix or some other IDE and just focus on sending the random number query and capturing the response. Once you can get that down, it should be easier to integrate into your project.

**Comment by YukioDev85** [comment]
Thanks for your kind answer.
But In my opinion, I think fulfillRandomness function is not called, because, I make the event in fulfillRandomess function but it is not logged.
I am using version 0.6 so, I am not sure why this issue is occured.
https://mumbai.polygonscan.com/address/0xC1fbB19cf8593E1d17F1EE0f56a1c6E8d828A79d#events
If you can make some time for me, Please check this contract.
I deployed and also I called the Flip function, you can see it.
But As you can see, in events, the event that I make in fulfillRandomness function was not logged.
I am waiting for your help.
Thanks.

**Comment by andrew-fleming** [comment]
I'm not sure I understand. The events _are_ logged—change the fourth drop-down menu to text on both events. You'll see `Loser` and `Bet`.

Hex: `4c6f736572000000000000000000000000000000000000000000000000000000`
equates to:
Text: `Loser`

---

Hex: `4265740000000000000000000000000000000000000000000000000000000000 `
equates to:
Text: `Bet`

**Comment by andrew-fleming** [comment]
You have it set up correctly already :) it just shows `hex` by default on the explorer

**Comment by samurai-techlead** [comment]
Thanks, Got it.

**Comment by samurai-techlead** [comment]
But If so, contractBalance variable should changed, but not changed.
So, I think many be somthing wrong.
Please give me your feedback.

**Comment by andrew-fleming** [comment]
Hmm it looks good to me. The contract started with 2 MATIC. You bet 1 MATIC and lost; therefore, the contract should have 3, correct?

**Comment by samurai-techlead** [comment]
Yes, Correct, but not changed.

**Comment by andrew-fleming** [comment]
Haha that is changed from 2 to 3. If you bet 1 MATIC again but this time you win, the contract balance will go down to 2 and 2 MATIC will be in your address's mapping.

**Comment by samurai-techlead** [comment]
Awesome, It is changed, but It takes some time???

**Comment by andrew-fleming** [comment]
Yeah, I set it up so that the balances aren't updated until the callback is received from Chainlink. You can refactor and update the balance right away and again after the callback if you'd like.

**Comment by samurai-techlead** [comment]
It takes long until change.
To speed up, we have to increase the fee, right?

**Comment by samurai-techlead** [comment]
Now set fee is to 0.0001 LINK, so to speed up, we can set fee to over 0.0001LINK.
This is my opinion, is it right?

**Comment by andrew-fleming** [comment]
Unfortunately, I don't think that'll help. The reason it takes some time is because Chainlink has to wait for your contract's tx, and then your contract has to wait for Chainlink's tx thereafter.

**Comment by andrew-fleming** [comment]
You could use pseudo-randomness for speed (if verifiable randomness is not a priority) if you'd like with something like `block.timestamp % 2`

**Comment by YukioDev85** [comment]
Thanks, You are excellent.
Can I ask if I have question in the future?
If is it Ok, could you let me know your name and the contracts(like $kype, TG, etc).
Best regards.

**Comment by andrew-fleming** [comment]
My pleasure 🙏 I'm glad you got the contract working. And of course: my name is Andrew and the best way to reach out to me is on [flote.app](https://flote.app/user/andrewfleming). I'm also on [Twitter](https://twitter.com/_andrew_fleming).

**Comment by YukioDev85** [comment]
Thanks, You don't use Telegram or Skype?

**Comment by samurai-techlead** [comment]
All is fine.
